easy_admin:
    site_name: 'Db Auto Pneus'
    formats:
        number: '%d'
    entities:
        Promotion:
          class: App\Entity\Promotion
          label: 'Promotion'
          list:
            title: 'Promotion'
            fields:
              - { property: 'title', label: 'Titre'}
              - { property: 'amount', label: 'Montant'}
              - { property: 'type', type: 'choice', choices: [!php/const App\Entity\Promotion::TYPE_PERCENT, !php/const App\Entity\Promotion::TYPE_AMOUNT ], label: 'Type'}
              - { property: 'dateStart', label: 'Date de début'}
              - { property: 'dateEnd', label: 'Date de fin'}
              - { property: 'option', label: 'Option concernée par la promotion'}
              - { property: 'reprogrammation', label: 'Promotion reprogrammation'}
          form:
            title: 'Promotion'
            fields:
              - { property: 'title', label: 'Titre'}
              - { property: 'type', type: 'choice', choices: [!php/const App\Entity\Promotion::TYPE_PERCENT, !php/const App\Entity\Promotion::TYPE_AMOUNT ], label: 'Type'}
              - { property: 'dateStart', label: 'Date de début'}
              - { property: 'dateEnd', label: 'Date de fin'}
              - { property: 'option', label: 'Option concernée par la promotion'}

        BodyWorkFolio:
          class: App\Entity\BodyWorkFolio
          label: 'PortFolio Carrosserie'
          list:
            title: 'Portfolio Carrosserie'
            fields:
              - { property: 'name', label: 'Titre'}
          form:
            title: 'Portfolio Carrosserie'
            fields:
              - { property: 'name', label: 'Titre'}
              - { property: 'description', label: 'Description'}
              - { property: 'befores', type: 'collection', label: 'Avant', type_options: {entry_type: 'App\Form\ImageType', by_reference: false }}
              - { property: 'afters', type: 'collection', label: 'Après', type_options: {entry_type: 'App\Form\ImageType', by_reference: false }}

        MecanicFolio:
          class: App\Entity\MecanicFolio
          label: 'PortFolio Mécanique'
          list:
            title: 'Portfolio Mécanique'
            fields:
              - { property: 'name', label: 'Titre'}
          form:
            title: 'Portfolio Mécanique'
            fields:
              - { property: 'name', label: 'Titre'}
              - { property: 'description', label: 'Description'}
              - { property: 'images', type: 'collection', label: 'Images', type_options: {entry_type: 'App\Form\ImageType', by_reference: false }}

