security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory: 
            memory:
                users:
                    david:
                        password: davidaline
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: in_memory
            anonymous: false
            http_basic: ~

        main:
            anonymous: ~
