mentions_legales:
    path:         /mentions_legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentions-legales.html.twig

